// 1. Separate State Variables
const [exactTopic, setExactTopic] = useState(""); // The user's input
const [topicAnalysis, setTopicAnalysis] = useState<any>(null); // The AI's breakdown

// 2. Fix Analyze Topic Handler
const handleAnalyzeTopic = async () => {
    try {
        const response = await api.post('/api/v1/question-papers/analyze-topic', {
            topic: exactTopic, // Send user input
            class_level, subject, language
        });
        // DO NOT call setExactTopic(response.data.analysis)
        setTopicAnalysis(response.data); // Store analysis separately
    } catch (err) { ... }
};

// 3. Fix Generation API Call
const handleGeneratePaper = async () => {
    // Validate marks before sending
    const calculatedTotal = sections.reduce((sum, s) => sum + (s.num_questions * s.marks_per_question), 0);
    if (calculatedTotal !== maximum_marks) {
        alert(`Mark mismatch! Sections total ${calculatedTotal}, but paper max is ${maximum_marks}.`);
        return;
    }

    try {
        setLoading(true);
        const payload = {
            topic: exactTopic, // ALWAYS send the original user input
            analysis_id: topicAnalysis?.id, // Optional reference
            class_level, subject, language, difficulty,
            sections_config: sections.map(s => ({
                section_title: s.title,
                question_type: s.type, // Ensure type matches the title
                num_questions: s.num_questions,
                marks_per_question: s.marks_per_question
            }))
        };
        const response = await api.post('/api/v1/question-papers/generate', payload);
        // On success, show provider metadata
        console.log(`Generated by: ${response.data.generation_provider}`);
    } catch (err) {
        // BUG 6 FIX: Stop loading and show error, do not allow silent fallback
        setError(err.response?.data?.detail || "AI Service unavailable. Please try again.");
    } finally {
        setLoading(false);
    }
};